### ISSUE TITLE
getPlayer that connected from waterdog

### ISSUE THREAD

**Issue by MoQI1373** [Alemiz112/StarGate-Atlantis#10]
Is there a function to getPlayer that connected from waterdog?? Because lobby server and other server is not sync and if player nick from lobby server then he don't nick on other server.sry for bad English

**Comment by xxAROX** [comment]
Waterdog is not made for sync server-side content

**Comment by xxAROX** [comment]
But you can sync content with websockets [see here](https://docs.waterdog.dev/books/plugins/page/proxy-communication)

**Comment by Alemiz112** [comment]
Player instances can not be passed between different servers. That is not purpose of this project.
