### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ImHammer** [Alemiz112/StarGate-Atlantis#11]
[19:36:48] [StarGate-Atlantis thread/ERROR]: Can not connect to StarGate server!

Fatal error: Uncaught Error: Undefined constant 'pocketmine\PLUGIN_PATH' in phar:///home/container/PocketMine-MP.phar/src/pocketmine/utils/Utils.php:619
Stack trace:
#0 phar:///home/container/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php(242): pocketmine\utils\Utils::cleanPath('phar:///home/co...')
#1 phar:///home/container/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php(202): pocketmine\utils\MainLogger::printExceptionMessage(Object(RuntimeException))
#2 [internal function]: pocketmine\utils\MainLogger->pocketmine\utils\{closure}()
#3 phar:///home/container/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php(212): Threaded->synchronized(Object(Closure))
#4 phar:///home/container/plugins/StarGate-Atlantis.phar/src/alemiz/sga/client/StarGateSocket.php(68): pocketmine\utils\MainLogger->logException(Object(RuntimeException))
#5 phar:///home/container/plugins/StarGate-Atlantis.phar/src/alemiz/sga/client/StarGateConnection.php(98): alemiz\sga\client\StarGateSocket->connect()
#6 [internal function]: alemiz\sg in phar:///home/container/PocketMine-MP.phar/src/pocketmine/utils/Utils.php on line 619

Warning: socket_close() expects parameter 1 to be resource, null given in phar:///home/container/plugins/StarGate-Atlantis.phar/src/alemiz/sga/client/StarGateSocket.php on line 77

Everything is set up correctly.

**Comment by Alemiz112** [comment]
This means that stargate client (pmmp plugin) can not connect to stargate server (proxy plugin).

**Comment by ImHammer** [comment]
Yes, I realized later, but you can help me with this: https://github.com/Alemiz112/StarGate/issues/8
