### ISSUE TITLE
Fatal Error - PocketMine Phar Update

### ISSUE THREAD

**Issue by mrpwes** [Alemiz112/StarGate-Atlantis#7]
version: 3.15.3 and 3.15.4

`[16:56:22] [Server thread/INFO]: Enabling StarGate-Atlantis v1.1.1
Fatal error: Cannot declare class Composer\Autoload\ComposerStaticInit2b8ac399219d8a04891c51782dcc70b3, because the name is already in use in phar:///home/container/PocketMine-MP.phar/vendor/composer/autoload_static.php on line 7`

**Comment by xxAROX** [comment]
```
Enabling StarGate-Atlantis v1.1.1

Fatal error: Cannot declare class Composer\Autoload\ComposerStaticInit3a116edf28463c3e1b7c8795f791c6c3, because the name is already in use in phar://C:/Users/kfeig/Desktop/PMMP/Network/PocketMine-MP/PocketMine-MP.phar/vendor/composer/autoload_static.php on line 7
[StarGate-Atlantis] Reloading StarGate Client default
version
This server is running PocketMine-MP 3.16.0 for Minecraft: Bedrock Edition v1.16.100 (protocol version 419)
```

Tested on Windows 10

**Comment by Alemiz112** [comment]
Hello, please use latest (dev) build of StarGateAtlantis from poggit. It was already fixed.

**Comment by xxAROX** [comment]
kk
